### ISSUE TITLE
Variables to Provide Key 

### ISSUE THREAD

**Issue by directorfury192** [temoTxt/Stress_Strain_Analysis_Tools#4]
Please provide a Type Specimen Key that provides the following information, read from the filename which will include _typei_, _typeiv_, or _d3039:

**Specimen**   Area        Gage Length
Type I               41.6         50
Type IV             19.2         25
D3039               82.5        180

**Comment by directorfury192** [comment]
This folder has python scripts i have written that could provide usable starting points to do this.  Let me know what you think. [https://onedrive.live.com/?id=C7858221CE2FBE53%21273629&cid=C7858221CE2FBE53](url)

**Comment by directorfury192** [comment]
@tjm5114  so i think what we need to do here is in the data header scrub file, BEFORE we scrub the header information we need to read it.  Something like: 

open(filename) as temps:
   if ('Data Header')  in line:
       nb=line.split()
       specimen_type=nb[#]
       layer_thickness=nb[#]
       infill=nb[#]

Then scrub the header data throughout the file.  Now we can use the following:

if specimen_type = str('typei')
    gage_length = 50
    area = 41.6
elseif specimen_type=str(typeiv)
    gage_length=25
    area=19.2
elseif specimen_type=str(d3039)
    gage_length = 180
    area = 82.5


Where the nb[#] corresponds to the point in the line where we have the type.  Also, @Nsearchof I want to change what we put in the data header.  The underscores there make the line split function difficult.  I want to be able to pull the Specimen Type, Layer Thickness, and Infill out and make those separate variables.  I think we can use them for data parsing.

Thoughts?

**Comment by Nsearchof** [comment]
Sounds good, I have a few questions for you both for clarity. 

- Is the data header change for the completed tests or for those moving forward. (Or both) (Since you and the kiddies have more testing, I can update that in the system so that it’s good moving forward)
-what is the preferred data header format?
-will the file renaming for existing files be automated? Or manually done to facilitate the data parsing?
- Is this change something we are applying to both tensile and fatigue data collection and code? Or is it more beneficial for one than the other? (So that I can rename my fatigue data as well)

**Comment by directorfury192** [comment]
Only moving forward should the data header change. I'm thinking my tests.
Not the kiddies. Unless they want to do manual changes to the data header.

I am still thinking about what the header should be. I'm thinking if we had
spaces in lieu of underscores that would make splitting the line easier.

Both maybe. Does the fatigue data need unique constants based on the
specimen type?  If you need the unique gage length and x-sectional area
then yes. It's important.

**Comment by temoTxt** [comment]
@directorfury192  can you just read the file name and parse up it's name to get those parameters and if it's tensile or fatigue? Perhaps coming up with a file name convention would make it easier if you didn't already have one.

**Comment by directorfury192** [comment]
Yes I could. But the file name is the same as the data header. It's all one
word. I need one part of the file name.

**Comment by temoTxt** [comment]
you just use a split string on the underscore(_) and that will return to a list of each word without the underscore.

something like:

split_file_name = file_name.split('_')

Then you can index each word by split_file_name[0], split_file_name[1], etc.

**Comment by directorfury192** [comment]
Ok cool. That makes sense.  Didn't realize I could do that. Shouldn't need
to change anything then. Will noodle today and report back

**Comment by directorfury192** [comment]
Completed.  See below:

for i in range(0, 4):
    layer_infill = ['0.254_solid_', '0.3302_solid_', '0.254_hd_', '0.3302_hd_']
    file_front = 'data/' + str(layer_infill[i])
    # print(file_front)
    for j in range(0,2):
        printer = ['uprint', 'dimension']
        file_middle = file_front + str(printer[j]) + '_'
        # print(file_middle)
        for k in range(0,2):
            type = ['typei', 'typeiv']
            file_back = file_middle + str(type[k])
            for n in range(0, 2):
                raster = ['_4545_', '_090_']
                file_last = file_back + str(raster[n]) + 'r('
                for replicates in range(1, 11):
                    file = file_last + str(replicates) + ').dat'
                    # print(file)
                    split_filename = file.split('_')
                    specimen_type = split_filename[3]
                    printer = split_filename[2]
                    layer = split_filename[0]
                    split_layer = layer.split('/')
                    layer_thickness = split_layer[1]
                    infill = split_filename[1]
