### ISSUE TITLE
Toe Compensation of Stress

### ISSUE THREAD

**Issue by directorfury192** [temoTxt/Stress_Strain_Analysis_Tools#5]
So we have added the TCStrain by using the Offset = slope/intercept we already created.  TCStrain = data['Strain']-Offset. 

Now what we need is to "vlookup" the offset value we just calculated within the column called Strain.  Then we need to pull the Stress value from that associated line.  That stress value becomes the TCStress for our first TCStrain row (i.e., 0 mm/mm).  The remaining rows for TCStress are sequential from the Strain column.  That is, if the Offset value came from Strain row 25, then the first TCStress value at TCStrain = 0 would be the Stress value from row 25.  That would now go in the TCStrain for row 0.  Then TCStrain row 1 = Stress value row 26, and so on.  That is how you toe compensate.  We would then graph the toe compensated stress v. strain (TCStress v. TCStrain) and recalculated the slope and y-intercept (i.e., TC_Slope and TC_Intercept).   in my next post i will talk about how TC_Slope = Final Elastic Modulus and TC_intercept is used to calculate the starting point of your 0.2% offset line.

Look at making a new data frame for this and making an inequality statement.

**Comment by directorfury192** [comment]
So i was able to get the TC Strain data to shift up getting rid of any negative values without loosing the rest of our data.  But I'm still struggling with getting the vlookup feature to do what i want it todo.  I'm thinking of dumping the dataframe into an excel file and then manipulating the excel file through python and the xlsxwriter engine.  That might be easier than reindexing or joining which don't seem to be giving me what i need

**Comment by directorfury192** [comment]
got the TC to work.  Graphed to confirm TC Stress v TC Strain has shifted.  But there are gaps in the stress data.  I think b/c i used merge instead of merge_asof.  But when I use merge_asof it keeps getting mad at me b/c all the values are not filled in in the tables.  I think there may be gaps in my data going further back.  Need to check upstream dataframes.  Probably around where I deleted all the negative values of TC Strain.

**Comment by tjm5114** [comment]
Sometimes the merge function drops duplicate values of a column.

I think you should create a new data frame object based upon a value
greater than your tc_x value and then grab the tc_y column as the new value.

Sorry I don't remember if stress or strain is x or y.

**Comment by directorfury192** [comment]
Thanks. I'll try that tomorrow!!

**Comment by tjm5114** [comment]
Can you commit and push your code in the mean time?

**Comment by directorfury192** [comment]
I thought I already did. I will check again

**Comment by directorfury192** [comment]
It's all in there.

**Comment by directorfury192** [comment]
I don't think its a duplication issue.  I think its a "exact match" issue between my two key columns.  I have already created a new dataframe to hold these values that you suggested.  The error message when i use merge_asof (code is: tcstressdata = pd.merge_asof(tcdata, vlookup, on='Strain', by='Stress', allow_exact_matches=False) )is:  ValueError: Merge keys contain null values on left side

I think its b/c when i shifted the rows up, it just made the last 135 rows blank instead of the first 135.  I have a few ideas on how to fix it.  I think i just need to reorder some of my steps.  I'll keep you posted.

**Comment by directorfury192** [comment]
Ok i was able to get merge_asof to work.  I have cleaned up the data and i have the TC graphs.  See attached.  I am putting in a separate ticket to remove the negative data at the end of the curve.  

The Max Load is 1038.5106 N
The Max Stress is 24.964197115384618 MPa
The Elastic Modulus is 690.0179375959734
The unshifted y-intercept is -1.466005486028823
The R-Value is 0.9881099143305594
The P-Value is 0.0
The Standard Error is 4.811196999437295
The Toe Compensation Offset is 0.002124590399977709 mm/mm
![Figure_3](https://user-images.githubusercontent.com/45216857/56296455-8de30000-60fc-11e9-8277-4b7a4c78d3ae.png)
![Figure_4](https://user-images.githubusercontent.com/45216857/56296456-8e7b9680-60fc-11e9-93ba-ab3786a890eb.png)
![Figure_1](https://user-images.githubusercontent.com/45216857/56296457-8e7b9680-60fc-11e9-9e6e-206bdbbf34e8.png)
![Figure_2](https://user-images.githubusercontent.com/45216857/56296458-8e7b9680-60fc-11e9-9a72-fbb6447a25d0.png)





The Toe Compensated Elastic Modulus is 686.6225183716188
The Toe Compensated y-intercept is 0.01803604822121674
The R-Value of the linear regression fit is 0.994291788603191
The P-Value is 0.0
The Standard Error of the fit is 2.788822367330254
